"""initial schema

Revision ID: 6bd53bd8f7a5
Revises:
Create Date: 2026-09-15 10:39:04.587598

Hand-written (not autogenerated) — this machine's local PostgreSQL only
has credentials known to Roy (cleared from disk per Phase 0's own
hardening handoff), so there was no live DB to autogenerate against.
Mirrors `central_governance_api.models` exactly as of v11 skeleton;
regenerate with `--autogenerate` once a real dev DB/role exists to
confirm there's no drift.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "6bd53bd8f7a5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_APPROVAL_STATUSES = (
    "pending",
    "accepted",
    "rejected",
    "executing",
    "applied",
    "failed_definite",
    "failed_unknown",
    "expired",
    "cancelled",
)
_FINDING_TYPES = ("requester_assertion", "admin_verified", "late_report")
_FINDING_CONCLUSIONS = (
    "confirmed_not_executed",
    "confirmed_executed",
    "inconclusive",
)


def upgrade() -> None:
    op.create_table(
        "pending_approval_records",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
        ),
        sa.Column("request_id", sa.String(64), nullable=False),
        sa.Column("tenant_scope", sa.String(64), nullable=False),
        sa.Column("requester_subject", sa.String(512), nullable=False),
        sa.Column("origin_device_id", sa.String(64), nullable=False),
        sa.Column("conversation_id", sa.String(128), nullable=False),
        sa.Column("action_event_id", sa.String(128), nullable=False),
        sa.Column("tool_call_id", sa.String(128), nullable=True),
        sa.Column("action_type", sa.String(128), nullable=False),
        sa.Column("tool_name", sa.String(128), nullable=False),
        sa.Column("policy_revision", sa.String(64), nullable=False),
        sa.Column("action_summary", sa.Text(), nullable=False),
        sa.Column("action_payload", postgresql.JSONB(), nullable=False),
        sa.Column("digest_salt", sa.String(64), nullable=True),
        sa.Column("action_payload_digest", sa.String(128), nullable=False),
        sa.Column("risk_level", sa.String(16), nullable=False),
        sa.Column("status", sa.String(32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("execution_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "executing_lease_expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("execution_attempt_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.CheckConstraint(
            f"status IN {_APPROVAL_STATUSES!r}", name="ck_approval_status_valid"
        ),
        sa.UniqueConstraint("request_id", name="uq_approval_request_id"),
    )
    op.create_index(
        "ix_pending_approval_records_request_id",
        "pending_approval_records",
        ["request_id"],
    )
    op.create_index(
        "ix_pending_approval_records_requester_subject",
        "pending_approval_records",
        ["requester_subject"],
    )
    op.create_index(
        "ix_pending_approval_records_status", "pending_approval_records", ["status"]
    )
    op.create_index(
        "ix_approval_requester_status",
        "pending_approval_records",
        ["requester_subject", "status"],
    )

    op.create_table(
        "approval_decisions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "approval_request_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("pending_approval_records.id"),
            nullable=False,
            unique=True,
        ),
        sa.Column("decision", sa.String(16), nullable=False),
        sa.Column("decision_actor_subject", sa.String(512), nullable=False),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('accepted', 'rejected')", name="ck_decision_value"
        ),
    )

    op.create_table(
        "reconciliation_findings",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "approval_request_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("pending_approval_records.id"),
            nullable=False,
        ),
        sa.Column("finding_type", sa.String(32), nullable=False),
        sa.Column("conclusion", sa.String(32), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("verifier_subject", sa.String(512), nullable=False),
        sa.Column("evidence", postgresql.JSONB(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint(
            f"finding_type IN {_FINDING_TYPES!r}", name="ck_finding_type_valid"
        ),
        sa.CheckConstraint(
            f"conclusion IS NULL OR conclusion IN {_FINDING_CONCLUSIONS!r}",
            name="ck_finding_conclusion_valid",
        ),
    )
    op.create_index(
        "ix_reconciliation_findings_approval_request_id",
        "reconciliation_findings",
        ["approval_request_id"],
    )

    op.create_table(
        "device_registrations",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("owner_subject", sa.String(512), nullable=False),
        sa.Column("device_id", sa.String(64), nullable=False, unique=True),
        sa.Column(
            "registered_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by_subject", sa.String(512), nullable=True),
    )
    op.create_index(
        "ix_device_registrations_owner_subject",
        "device_registrations",
        ["owner_subject"],
    )
    op.create_index(
        "ix_device_registrations_device_id", "device_registrations", ["device_id"]
    )

    op.create_table(
        "device_denylist_entries",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("owner_subject", sa.String(512), nullable=False),
        sa.Column("device_id", sa.String(64), nullable=False),
        sa.Column(
            "denied_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.UniqueConstraint(
            "owner_subject", "device_id", name="uq_denylist_owner_device"
        ),
    )

    op.create_table(
        "admin_audit_events",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("event_type", sa.String(64), nullable=False),
        sa.Column("actor_subject", sa.String(512), nullable=False),
        sa.Column("origin_device_id", sa.String(64), nullable=True),
        sa.Column(
            "approval_request_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("pending_approval_records.id"),
            nullable=True,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(), nullable=False),
    )
    op.create_index(
        "ix_admin_audit_events_event_type", "admin_audit_events", ["event_type"]
    )
    op.create_index(
        "ix_admin_audit_events_actor_subject", "admin_audit_events", ["actor_subject"]
    )

    op.create_table(
        "idempotency_records",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("scope_principal", sa.String(512), nullable=False),
        sa.Column("scope_endpoint", sa.String(128), nullable=False),
        sa.Column("scope_resource_id", sa.String(128), nullable=False),
        sa.Column("idempotency_key", sa.String(128), nullable=False),
        sa.Column("request_fingerprint", sa.String(128), nullable=False),
        sa.Column("response_snapshot", postgresql.JSONB(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.UniqueConstraint(
            "scope_principal",
            "scope_endpoint",
            "scope_resource_id",
            "idempotency_key",
            name="uq_idempotency_scope",
        ),
    )


def downgrade() -> None:
    op.drop_table("idempotency_records")
    op.drop_table("admin_audit_events")
    op.drop_table("device_denylist_entries")
    op.drop_table("device_registrations")
    op.drop_table("reconciliation_findings")
    op.drop_table("approval_decisions")
    op.drop_table("pending_approval_records")
